////URLL-version=3;
//// https://github.com/seanpm2001/URLL-Specification/
//// DeGoogle repository listing as of 2023, Wednesday, June 7th at 9:59 pm PST
//// ----------------------------------------------------------------------------------------- ////
//// START:
https://github.com/seanpm2001/Degoogle-your-life
https://github.com/seanpm2001/Degoogled_Android_Phone_VM_Research
https://github.com/seanpm2001/Google-security-issues
https://github.com/seanpm2001/What-the-FLoC
https://github.com/seanpm2001/Why-you-should-stop-using-Chrome
https://github.com/seanpm2001/Its-time-to-cut-WideVine-DRM
https://github.com/seanpm2001/DeGoogle-your-Life_Wiki_2021
https://github.com/seanpm2001/Widevine-l3-decryptor-wiki
https://github.com/seanpm2001/Google-performance-issues
https://github.com/seanpm2001/Stop-using-Chromebooks
https://github.com/seanpm2001/Stop-Googling--Why-you-should-stop-using-Google-Search
https://github.com/seanpm2001/Alternating-from-YouTube
https://github.com/seanpm2001/Why-you-should-stop-using-Gerrit
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Analytics
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Tenor
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Drawings
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Survey-rewards
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Calculator
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Camera
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Summer-of-code
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Base
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Keep
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Stadia
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Fi
https://github.com/seanpm2001/Why-you-should-stop-using-VirusTotal
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Calendar
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Photos
https://github.com/seanpm2001/Why-you-should-stop-using-Google-VPN
https://github.com/seanpm2001/Why-you-should-stop-using-Android-Pay
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Pay
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Sites_New
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Sites_Classic
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Video
https://github.com/seanpm2001/Why-you-should-stop-using-Google-WebM
https://github.com/seanpm2001/Why-you-should-stop-using-Google-WebP
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Dart
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Go
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Flutter
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Blockly
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Tensorflow
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Duo
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Hangouts
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Nest
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Home
https://github.com/seanpm2001/Why-you-should-stop-using-GBoard
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Fuchsia
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Glass
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Material-Design
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Messages
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Cardboard
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Forms
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Sheets
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Slides
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Docs
https://github.com/seanpm2001/Why-you-should-stop-using-the-Google-Play-Store
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Plus
https://github.com/seanpm2001/Why-you-should-stop-using-Google-One
https://github.com/seanpm2001/Why-you-should-stop-using-Google-AdSense
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Accounts
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Translate
https://github.com/seanpm2001/Stop-reading-from-Google-Books
https://github.com/seanpm2001/Why-you-should-stop-using-Google-maps-and-Google-Earth
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Drive
https://github.com/seanpm2001/Why-you-should-stop-using-Android
https://github.com/seanpm2001/Why-you-should-stop-using-ReCaptcha
https://github.com/seanpm2001/Why-you-should-stop-using-GMail
https://github.com/seanpm2001/Why-you-should-avoid-Google-AMP
https://github.com/seanpm2001/Hey-Google-Stop
https://github.com/seanpm2001/Stop-using-Google-Classroom
https://github.com/seanpm2001/Problems-with-the-Google-Knowledge-Graph
https://github.com/seanpm2001/Why-you-should-avoid-Google-News
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Images
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Movies
https://github.com/seanpm2001/DeGoogle-your-life-Current-Catalogue
https://github.com/seanpm2001/DeGoogle-your-life-Graveyard-catalogue
https://github.com/seanpm2001/DeGoogle-your-life-Full-catalogue
https://github.com/seanpm2001/DeGoogle-Ranking-Scale
https://github.com/seanpm2001/Google-is-a-monopoly
https://github.com/seanpm2001/Google-Outage-History
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Looker
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Safe-Browsing
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Play-Movies
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Pixel
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Nexus
https://github.com/seanpm2001/Why-you-should-have-avoided-Google-Plus
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Scholar
https://github.com/seanpm2001/Why-you-should-have-avoided-Google-Stadia
https://github.com/seanpm2001/Why-you-should-stop-using-Google-ReCaptcha
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Fiber
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Families
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Gallery
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Peridot
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Fonts
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Fit
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Travel
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Zircon
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Suite-GSuite
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Lens
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Topaz
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Trips
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Store
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Station
https://github.com/seanpm2001/Why-you-should-have-avoided-Google-SMS
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Stackdriver
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Tasks
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Meet
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Discover
https://github.com/seanpm2001/Why-you-should-not-be-a-Google-Developer
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Currents
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Cloud-Services
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Apps-Script
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Capital
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Chat
https://github.com/seanpm2001/Why-you-should-stop-using-Google-AdWords
https://github.com/seanpm2001/Why-you-should-stop-using-Google-AdMob
https://github.com/seanpm2001/Why-you-should-stop-using-Google-FireBase
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Dropcam
https://github.com/seanpm2001/Why-you-should-stop-using-Google-DoubleClick
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Arts-and-Culture
https://github.com/seanpm2001/Why-you-should-stop-using-Google-AlphaGo
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Cloud-Print
https://github.com/seanpm2001/Why-you-should-stop-using-Google-For-Education
https://github.com/seanpm2001/Why-you-should-stop-using-Google-For-Startups
https://github.com/seanpm2001/Why-you-should-not-attend-Google-IO
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Incognito-Mode
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Jamboard
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Podcasts
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Orkut
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Kubernetes
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Jigsaw
https://github.com/seanpm2001/Why-you-should-stop-using-Google-Workspace
https://github.com/seanpm2001/Why-you-should-stop-using-Google-WebDriver
//// END.
//// Repo count: 132
//// ----------------------------------------------------------------------------------------- ////
//// Related projects:
//// The REAL Data liberation front (2 repositories)
https://github.com/seanpm2001/The-REAL-Data-Liberation-Front
https://github.com/seanpm2001/The-REAL-Data-Liberation-Front_Docs
//// Go-ogle (1 repository)
https://github.com/seanpm2001/Go-ogle
//// NetM project (3 repositories)
https://github.com/seanpm2001/NetV
https://github.com/seanpm2001/NetM
https://github.com/seanpm2001/NetP
//// Seanpm2001 life archive (4 repositories)
https://github.com/seanpm2001/GSoC
https://github.com/seanpm2001/Seanpm2001-GSoC
https://github.com/seanpm2001/Seanpm2001-Google
https://github.com/seanpm2001/YouTube
//// Candroid (28 repositories)
https://github.com/seanpm2001/Candroid
https://github.com/seanpm2001/Candroid-Catalogue
https://github.com/seanpm2001/Candroid-Docs
https://github.com/seanpm2001/Candroid-App-Store
https://github.com/seanpm2001/Candroid-Assistant
https://github.com/seanpm2001/Candroid-Battery-Monitor
https://github.com/seanpm2001/Candroid-Browser
https://github.com/seanpm2001/Candroid-Camera
https://github.com/seanpm2001/Candroid-Calculator
https://github.com/seanpm2001/Candroid-Calendar
https://github.com/seanpm2001/Candroid-Clock
https://github.com/seanpm2001/Candroid-Debug
https://github.com/seanpm2001/Candroid-Contacts
https://github.com/seanpm2001/Candroid-Easter-Egg
https://github.com/seanpm2001/Candroid-Flashlight
https://github.com/seanpm2001/Candroid-Keyboard
https://github.com/seanpm2001/Candroid-Mail
https://github.com/seanpm2001/Candroid-Market
https://github.com/seanpm2001/Candroid-Notepad
https://github.com/seanpm2001/Candroid-Photo-Viewer
https://github.com/seanpm2001/Candroid-Phone
https://github.com/seanpm2001/Candroid-Rotate
https://github.com/seanpm2001/Candroid-Settings
https://github.com/seanpm2001/Candroid-Tube
https://github.com/seanpm2001/Candroid-TV
https://github.com/seanpm2001/Candroid-Video
https://github.com/seanpm2001/Candroid-Voicemail
https://github.com/seanpm2001/Candroid-Wallpaper
//// Android x128 (2 repositories)
https://github.com/seanpm2001/Android-x128
https://github.com/seanpm2001/Android-x128_Docs
//// Android x64 (90 repositories)
https://github.com/seanpm2001/Android-x64
https://github.com/seanpm2001/Android-x64_Docs
https://github.com/seanpm2001/Android-x64_Workspace_Firefox
https://github.com/seanpm2001/Android-x64_LiveCD_15A
https://github.com/seanpm2001/Android-x64_LiveCD_14A
https://github.com/seanpm2001/Android-x64_LiveCD_13A
https://github.com/seanpm2001/Android-x64_LiveCD_12C
https://github.com/seanpm2001/Android-x64_LiveCD_12B
https://github.com/seanpm2001/Android-x64_LiveCD_12A
https://github.com/seanpm2001/Android-x64_LiveCD_11A
https://github.com/seanpm2001/Android-x64_LiveCD_10A
https://github.com/seanpm2001/Android-x64_LiveCD_9C
https://github.com/seanpm2001/Android-x64_LiveCD_9B
https://github.com/seanpm2001/Android-x64_LiveCD_9A
https://github.com/seanpm2001/Android-x64_LiveCD_8C
https://github.com/seanpm2001/Android-x64_LiveCD_8B
https://github.com/seanpm2001/Android-x64_LiveCD_8A
https://github.com/seanpm2001/Android-x64_LiveCD_7C
https://github.com/seanpm2001/Android-x64_LiveCD_7B
https://github.com/seanpm2001/Android-x64_LiveCD_7A
https://github.com/seanpm2001/Android-x64_LiveCD_6C
https://github.com/seanpm2001/Android-x64_LiveCD_6B
https://github.com/seanpm2001/Android-x64_LiveCD_6A
https://github.com/seanpm2001/Android-x64_LiveCD_5C
https://github.com/seanpm2001/Android-x64_LiveCD_5B
https://github.com/seanpm2001/Android-x64_LiveCD_5A
https://github.com/seanpm2001/Android-x64_Android15.0_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android15.0_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android15.0_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android15.0_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android14.0_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android14.0_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android14.0_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android14.0_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android13_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android13_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android13_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android13_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android12.1_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android12.1_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android12.1_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android12.1_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android12_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android12_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android12_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android12_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android11_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android11_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android11_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android11_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android10_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android10_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android10_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android10_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android9_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android9_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android9_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android9_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android8.1_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android8.1_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android8.1_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android8.1_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android8.0_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android8.0_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android8.0_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android8.0_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android7.1_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android7.1_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android7.1_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android7.1_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android7.0_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android7.0_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android7.0_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android7.0_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android6.1_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android6.1_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android6.1_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android6.1_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android6.0_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android6.0_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android6.0_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android6.0_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android5.1_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android5.1_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android5.1_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android5.1_LiveCD_Edition
https://github.com/seanpm2001/Android-x64_Android5.0_Heavy_Edition
https://github.com/seanpm2001/Android-x64_Android5.0_Vanilla_Edition
https://github.com/seanpm2001/Android-x64_Android5.0_DeGoogled_Edition
https://github.com/seanpm2001/Android-x64_Android5.0_LiveCD_Edition
//// Android x32x64 (18 repositories)
https://github.com/seanpm2001/Android-x32x64
https://github.com/seanpm2001/Android-x32x64_Docs
https://github.com/seanpm2001/Android-x32x64_LiveCD_15A_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_14A_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_13A_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_12B_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_12A_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_11A_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_10A_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_9A_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_8B_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_8A_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_7B_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_7A_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_6B_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_6A_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_5B_Edition
https://github.com/seanpm2001/Android-x32x64_LiveCD_5A_Edition
//// Android x32 (121 repositories)
https://github.com/seanpm2001/Android-x32
https://github.com/seanpm2001/Android-x32_Docs
https://github.com/seanpm2001/Android-x32_LiveCD_4.4C
https://github.com/seanpm2001/Android-x32_LiveCD_4.4B
https://github.com/seanpm2001/Android-x32_LiveCD_4.4A
https://github.com/seanpm2001/Android-x32_LiveCD_4.3C
https://github.com/seanpm2001/Android-x32_LiveCD_4.3B
https://github.com/seanpm2001/Android-x32_LiveCD_4.3A
https://github.com/seanpm2001/Android-x32_LiveCD_4.2C
https://github.com/seanpm2001/Android-x32_LiveCD_4.2B
https://github.com/seanpm2001/Android-x32_LiveCD_4.2A
https://github.com/seanpm2001/Android-x32_LiveCD_4.1C
https://github.com/seanpm2001/Android-x32_LiveCD_4.1B
https://github.com/seanpm2001/Android-x32_LiveCD_4.1A
https://github.com/seanpm2001/Android-x32_LiveCD_4.0C
https://github.com/seanpm2001/Android-x32_LiveCD_4.0B
https://github.com/seanpm2001/Android-x32_LiveCD_4.0A
https://github.com/seanpm2001/Android-x32_LiveCD_3.2C
https://github.com/seanpm2001/Android-x32_LiveCD_3.2B
https://github.com/seanpm2001/Android-x32_LiveCD_3.2A
https://github.com/seanpm2001/Android-x32_LiveCD_3.1C
https://github.com/seanpm2001/Android-x32_LiveCD_3.1B
https://github.com/seanpm2001/Android-x32_LiveCD_3.1A
https://github.com/seanpm2001/Android-x32_LiveCD_3.0C
https://github.com/seanpm2001/Android-x32_LiveCD_3.0B
https://github.com/seanpm2001/Android-x32_LiveCD_3.0A
https://github.com/seanpm2001/Android-x32_LiveCD_2.3C
https://github.com/seanpm2001/Android-x32_LiveCD_2.3B
https://github.com/seanpm2001/Android-x32_LiveCD_2.3A
https://github.com/seanpm2001/Android-x32_LiveCD_2.2C
https://github.com/seanpm2001/Android-x32_LiveCD_2.2B
https://github.com/seanpm2001/Android-x32_LiveCD_2.2A
https://github.com/seanpm2001/Android-x32_LiveCD_2.1C
https://github.com/seanpm2001/Android-x32_LiveCD_2.1B
https://github.com/seanpm2001/Android-x32_LiveCD_2.1A
https://github.com/seanpm2001/Android-x32_LiveCD_2.0C
https://github.com/seanpm2001/Android-x32_LiveCD_2.0B
https://github.com/seanpm2001/Android-x32_LiveCD_2.0A
https://github.com/seanpm2001/Android-x32_LiveCD_1.6C
https://github.com/seanpm2001/Android-x32_LiveCD_1.6B
https://github.com/seanpm2001/Android-x32_LiveCD_1.6A
https://github.com/seanpm2001/Android-x32_LiveCD_1.5C
https://github.com/seanpm2001/Android-x32_LiveCD_1.5B
https://github.com/seanpm2001/Android-x32_LiveCD_1.5A
https://github.com/seanpm2001/Android-x32_LiveCD_1.1C
https://github.com/seanpm2001/Android-x32_LiveCD_1.1B
https://github.com/seanpm2001/Android-x32_LiveCD_1.1A
https://github.com/seanpm2001/Android-x32_LiveCD_1.0B
https://github.com/seanpm2001/Android-x32_LiveCD_1.0A
https://github.com/seanpm2001/Android-x32_LiveCD_1.0C
https://github.com/seanpm2001/Android-x32_LiveCD_0.9C
https://github.com/seanpm2001/Android-x32_LiveCD_0.9B
https://github.com/seanpm2001/Android-x32_LiveCD_0.9A
https://github.com/seanpm2001/Android-x32_Android4.4_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android4.4_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android4.4_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android4.4_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android4.3_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android4.3_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android4.3_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android4.3_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android4.2_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android4.2_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android4.2_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android4.2_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android4.1_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android4.1_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android4.1_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android4.1_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android4.0_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android4.0_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android4.0_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android4.0_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android3.2_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android3.2_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android3.2_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android3.2_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android3.1_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android3.1_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android3.1_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android3.1_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android3.0_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android3.0_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android3.0_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android3.0_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android2.3_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android2.3_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android2.3_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android2.3_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android2.2_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android2.2_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android2.2_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android2.2_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android2.1_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android2.1_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android2.1_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android2.1_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android2.0_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android2.0_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android2.0_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android2.0_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android1.6_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android1.6_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android1.6_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android1.6_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android1.5_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android1.5_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android1.5_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android1.5_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android1.1_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android1.1_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android1.1_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android1.1_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android1.0_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android1.0_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android1.0_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android1.0_LiveCD_Edition
https://github.com/seanpm2001/Android-x32_Android0.9_Heavy_Edition
https://github.com/seanpm2001/Android-x32_Android0.9_Vanilla_Edition
https://github.com/seanpm2001/Android-x32_Android0.9_DeGoogled_Edition
https://github.com/seanpm2001/Android-x32_Android0.9_LiveCD_Edition
//// Other (1 repository)
https://github.com/seanpm2001/Please-do-NOT-turn-off-your-adblocker
//// END.
//// ----------------------------------------------------------------------------------------- ////
//// Repo count: 270
//// Combined repository count: 402
//// FILE INFO:
//// File version: 25 (2023, Wednesday, June 7th at 9:59 pm PST)
//// Line count (including blank lines and compiler line): 430
//// End of file
